"use client";

import { useState } from "react";
import {
  User,
  ChevronUp,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  X,
  Pencil,
  MapPin,
  ShieldCheck,
  Car,
  Baby,
  Globe,
  Clock,
  Heart,
  Check,
  Sparkles,
  Stethoscope,
  CigaretteOff,
  PawPrint,
  Users,
  GraduationCap,
  Award,
  Briefcase,
  BookOpen,
  HandHeart,
  Smile,
  CalendarCheck,
  Accessibility,
  ThumbsUp,
  Languages,
} from "lucide-react";
import { cn } from "@/lib/utils";

// ╔══════════════════════════════════════════════════════════════════════════════╗
// ║  MOCK DATA                                                                 ║
// ║                                                                            ║
// ║  Organised by source:                                                      ║
// ║    • HERO — identity fields shown on the hero card                         ║
// ║    • AI CONTENT — ai_content JSONB fields (generated by OpenAI)            ║
// ║    • STRUCTURED — nannies table / nanny_leads fields (NOT ai-generated)    ║
// ║                                                                            ║
// ║  Each field shows its proposed JSONB key or table column                   ║
// ╚══════════════════════════════════════════════════════════════════════════════╝

// ── HERO (from user_profiles + nannies table) ────────────────────────────────

const MOCK_HERO = {
  firstName: "Sarah",
  age: 27,
  suburb: "Bondi",
  profilePictureUrl: null as string | null,
  isVerified: true,
  verificationLevel: 4,
  // additional_photos — up to 3 photos uploaded during onboarding (from nanny_images table)
  additionalPhotos: [] as string[], // real photos go here
  // placeholder colours for visualization
  additionalPhotoColors: ["bg-rose-400", "bg-sky-400", "bg-amber-400"],
};

// ── AI CONTENT — ai_content JSONB ────────────────────────────────────────────

// ai_content.headline — tagline in hero (~15-20 words)
const MOCK_AI_HEADLINE = "I'm a patient and creative nanny who loves building fun, safe spaces where children grow with confidence. Your little ones will always feel supported, engaged and free to explore with me by their side.";

// ┌──────────────────────────────────────────────────────────────────────────┐
// │  AI TONE GUIDE (for prompt rewrite)                                     │
// │                                                                         │
// │  All profile text must be first-person "I" statements.                  │
// │  Pattern: "I am {trait/value} so that you/your children {benefit}."     │
// │                                                                         │
// │  ✅  "I'm patient and creative, so your children feel safe to explore"  │
// │  ❌  "Your children will be in the hands of someone patient..."         │
// │                                                                         │
// │  The nanny speaks directly to the parent. She owns her qualities and    │
// │  connects each one to a concrete benefit for the family or child.       │
// └──────────────────────────────────────────────────────────────────────────┘

// ai_content.bio_summary.about — personal intro, who I am (~40-50 words)
// Draws from: identity.motivation
// Tone: first-person, connects passion → benefit for the family
const MOCK_AI_ABOUT = "<p>What I love most about childcare is giving children the best possible start — watching them grow in confidence and curiosity is what gets me up every morning. I bring that genuine passion into every day, so your family always has someone who truly cares.</p>";

// ai_content.bio_summary.personality — my personality → benefit for your children (~40-50 words)
// Draws from: identity.personality_traits (5 selected)
// Tone: first-person, "I am X so that your children Y"
const MOCK_AI_PERSONALITY = "<p>I'm patient and nurturing, so your children always feel safe and unhurried. I bring creativity and warmth into every interaction, which means little ones are engaged and happy throughout the day. I'm reliable and consistent, so your family can count on a calm, steady presence every time.</p>";

// ai_content.bio_summary.values — my values → benefit for parents and children (~40-50 words)
// Draws from: identity.professional_values (5 selected)
// Tone: first-person, "I believe in X so that your child Y"
const MOCK_AI_VALUES = "<p>I encourage independence, so your child builds confidence at their own pace. I teach through play, making learning feel natural and fun. I stay consistent and in tune with each child's needs, so routines run smoothly — and I adapt quickly when things change, so your family always feels supported.</p>";

// ai_content.bio_summary.background — childcare background narrative (~40-50 words)
// Draws from: experience.childcare_roles, qualifications.highest_qualification
// Tone: first-person, contextualises qualification + roles into a story
const MOCK_AI_BACKGROUND = "<p>I hold a Diploma of Early Childhood Education and Care, which gave me a strong foundation in child development and age-appropriate learning. Over the past 7 years I've worked across nannying, daycare and after-school care — each role teaching me something different about how children learn, play and grow.</p>";

// NOTE: Safety & Assurance is NOT ai-generated — it is computer-generated
// from structured data (verification_level, certificates, vaccination_status)

// ai_content.bio_summary.what_i_offer — family-focused services paragraph (~50-60 words)
// NEW: replaces old "services". Draws from:
//   - preferences.role_types
//   - identity.level_of_support
//   - preferences.min_age / max_age
// written from the family's benefit perspective
const MOCK_AI_WHAT_I_OFFER = "<p>Your family will receive dedicated mothers help and back-to-work support tailored around your routine. I provide hands-on engagement, play-based learning and educational guidance for children from newborn to 5 years — making the transition back to work or daily life smoother, less stressful and more joyful for everyone.</p>";

// ai_content.experience_summary — experience narrative (~60-80 words)
// Draws from: experience.total_experience, experience.childcare_roles,
//   experience.under_3_experience, experience.newborn_experience
const MOCK_AI_EXPERIENCE = "<p>With 7 years of childcare experience across nannying, daycare and after-school care, I've developed a deep understanding of what children need at every stage. Three of those years were spent working closely with children under 3, where I built strong skills in infant routines, feeding and sleep schedules. I also have a year of dedicated newborn care, learning the patience and gentleness that tiny ones need most.</p>";

// ── STRUCTURED DATA — from nannies table + nanny_leads ───────────────────────

// identity.motivation (single select from onboarding Q1)
// Options: "Supporting families" | "Developing young minds" |
//          "Giving children the best possible start" | "Making a real difference" |
//          "The flexibility" | "Other"
const MOCK_MOTIVATION = "Giving children the best possible start";

// identity.personality_traits (5 selected from onboarding Q2)
// Options: Patient, Creative, Energetic, Nurturing, Calm, Organised,
//          Warm, Reliable, Adaptable, Empathetic, Playful, Attentive
const MOCK_PERSONALITY_TRAITS = ["Patient", "Nurturing", "Creative", "Warm", "Reliable"];

// identity.professional_values (5 selected from onboarding Q3)
// Options: "Encouraging independence", "Being consistent and dependable",
//          "Staying calm under pressure", "Teaching through play",
//          "Taking accountability", "Adapting to each family's style",
//          "Being in tune with a child's needs", "Anticipating needs",
//          "Being open and transparent", "Understanding child development",
//          "Following routines with care", "Adapting quickly to change"
const MOCK_PROFESSIONAL_VALUES = [
  "Encouraging independence",
  "Teaching through play",
  "Being consistent and dependable",
  "Being in tune with a child's needs",
  "Adapting quickly to change",
];

// identity.level_of_support (single select from onboarding Q4)
// Options: "Supervision" | "Engagement and Play" | "Educational Support" | "Developmental Assistance"
const MOCK_LEVEL_OF_SUPPORT = "Educational Support";

// experience (from nannies table — numeric columns)
const MOCK_EXPERIENCE_STATS = {
  total_experience_years: 7,   // always shown if > 0
  under_3_experience_years: 3, // only shown if > 0
  newborn_experience_years: 1, // only shown if > 0
};

// experience.childcare_roles (from nanny_leads — array of {role, duration})
// Role options: Nanny, Babysitter, Au pair, Daycare, Pre-school,
//               School teacher, After-school care, Other
const MOCK_CHILDCARE_ROLES = [
  { role: "Nanny", duration: 4 },
  { role: "Daycare", duration: 2 },
  { role: "After-school care", duration: 1 },
];

// qualifications (from nanny_credentials table)
// Qualification options: "Certificate III in Early Childhood Education and Care",
//   "Certificate IV in Education Support", "Diploma of Early Childhood Education and Care",
//   "Bachelor of Early Childhood Education (Or Equivalent)"
const MOCK_QUALIFICATIONS = {
  highest_qualification: "Diploma of Early Childhood Education and Care",
  // Certificate options: "CPR", "First Aid", "First Aid in Education & Care Setting", "Child Protection"
  certificates: ["CPR", "First Aid", "Child Protection"],
};

// preferences (from nannies table)
// role_types options: "Mothers Help", "Back-to-Work Support", "Pick Up & Drop Off",
//                     "Child Development", "Home Management"
const MOCK_PREFERENCES = {
  role_types: ["Mothers Help", "Back-to-Work Support", "Child Development"],
  min_child_age_months: 0,   // "Newborn"
  max_child_age_months: 60,  // "5 years"
  max_children: 2,
  additional_needs: true,    // from preferences.additional_needs
};

// matching (from nannies table — boolean columns)
const MOCK_GOOD_TO_KNOW = {
  drivers_license: true,
  has_car: true,
  comfortable_with_pets: true,
  vaccination_status: true,
  non_smoker: true,
  nationality: "Australian",
  // language options: "English", "Foreign Language", "Multiple"
  languages: ["English"],
  other_languages: "French" as string | null, // e.g. "French, Mandarin"
};

// hourly rate (from nannies table)
const MOCK_RATE = {
  hourly_rate_min: 45,
};

// availability (from nanny_availability table — NOT ai-generated)
const MOCK_AVAILABILITY = {
  days_available: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
  schedule: {
    monday: ["Morning (6am-10am)", "Midday (10am-2pm)", "Afternoon (2pm-6pm)"],
    tuesday: ["Morning (6am-10am)", "Midday (10am-2pm)"],
    wednesday: ["Morning (6am-10am)", "Midday (10am-2pm)", "Afternoon (2pm-6pm)", "Evening (6pm-10pm)"],
    thursday: ["Midday (10am-2pm)", "Afternoon (2pm-6pm)"],
    friday: ["Morning (6am-10am)", "Midday (10am-2pm)"],
  } as Record<string, string[]>,
  immediate_start: true,
  placement_ongoing: true,
};

// Hero badge pills — experience stats (if > 0) + qualification only
const MOCK_BADGES: { icon: string; label: string; primary?: boolean }[] = [
  ...(MOCK_EXPERIENCE_STATS.total_experience_years > 0
    ? [{ icon: "Clock", label: `${MOCK_EXPERIENCE_STATS.total_experience_years} yrs experience`, primary: true }]
    : []),
  ...(MOCK_EXPERIENCE_STATS.under_3_experience_years > 0
    ? [{ icon: "Baby", label: `${MOCK_EXPERIENCE_STATS.under_3_experience_years} yrs under 3s`, primary: true }]
    : []),
  ...(MOCK_EXPERIENCE_STATS.newborn_experience_years > 0
    ? [{ icon: "Baby", label: `${MOCK_EXPERIENCE_STATS.newborn_experience_years} yr newborns`, primary: true }]
    : []),
  ...(MOCK_QUALIFICATIONS.highest_qualification
    ? [{ icon: "GraduationCap", label: MOCK_QUALIFICATIONS.highest_qualification }]
    : []),
];

// ╔══════════════════════════════════════════════════════════════════════════════╗
// ║  UI COMPONENTS — Layout & structure below, content from mock data above    ║
// ╚══════════════════════════════════════════════════════════════════════════════╝

// ── Availability Grid ────────────────────────────────────────────────────────

const DAYS = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"] as const;
const SLOT_LABELS = ["Morning", "Midday", "Afternoon", "Evening"];
const TIME_SLOTS = ["Morning (6am-10am)", "Midday (10am-2pm)", "Afternoon (2pm-6pm)", "Evening (6pm-10pm)"] as const;
const SLOT_RANGES = [
  { start: 6, end: 10 },
  { start: 10, end: 14 },
  { start: 14, end: 18 },
  { start: 18, end: 22 },
];

function normaliseDaySlots(raw: unknown): boolean[] {
  if (!raw) return [false, false, false, false];
  if (Array.isArray(raw)) {
    return TIME_SLOTS.map((slot) => raw.includes(slot));
  }
  if (typeof raw === "object" && raw !== null && "available" in raw) {
    const obj = raw as { available?: boolean; start?: string | null; end?: string | null };
    if (!obj.available || !obj.start || !obj.end) return [false, false, false, false];
    const startHour = parseInt(obj.start.split(":")[0]);
    const endHour = parseInt(obj.end.split(":")[0]);
    return SLOT_RANGES.map((range) => startHour <= range.start && endHour >= range.end);
  }
  return [false, false, false, false];
}

function AvailabilityGrid({ schedule, firstName }: { schedule: Record<string, unknown>; firstName: string }) {
  return (
    <>
      <div className="overflow-x-auto -mx-1">
        <table className="w-full text-sm">
          <thead>
            <tr>
              <th className="py-2 pr-3 text-left text-xs font-medium text-slate-400" />
              {SLOT_LABELS.map((label) => (
                <th key={label} className="px-1.5 py-2 text-center text-xs font-medium text-slate-400">{label}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {DAYS.map((day) => {
              const rawEntry = schedule[day.toLowerCase()];
              const slots = normaliseDaySlots(rawEntry);
              return (
                <tr key={day}>
                  <td className="py-1.5 pr-3 font-medium text-slate-600 text-sm whitespace-nowrap">{day.slice(0, 3)}</td>
                  {SLOT_LABELS.map((_, i) => (
                    <td key={i} className="px-1.5 py-1.5 text-center">
                      <span className={cn(
                        "inline-flex h-8 w-8 items-center justify-center rounded-lg text-xs transition-colors",
                        slots[i]
                          ? "bg-violet-500 text-white"
                          : "bg-slate-50 text-slate-200"
                      )}>
                        {slots[i] ? <Check className="h-3.5 w-3.5" /> : "–"}
                      </span>
                    </td>
                  ))}
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </>
  );
}

// ── Small UI helpers ─────────────────────────────────────────────────────────

function GlanceItem({ icon: Icon, label, variant = "default" }: { icon: React.ElementType; label: string; variant?: "default" | "green" }) {
  return (
    <div className={cn(
      "flex items-center gap-2.5 rounded-lg px-3 py-2.5",
      variant === "green" ? "bg-green-50" : "bg-slate-50",
    )}>
      <Icon className={cn("h-4 w-4 shrink-0", variant === "green" ? "text-green-600" : "text-violet-500")} />
      <span className={cn("text-sm", variant === "green" ? "text-green-700" : "text-slate-700")}>{label}</span>
    </div>
  );
}

function StatBox({ value, label }: { value: number; label: string }) {
  return (
    <div className="rounded-xl bg-slate-50 p-3 text-center">
      <p className="text-xl font-bold text-violet-600">{value}</p>
      <p className="text-xs text-slate-500">{label}</p>
    </div>
  );
}

function Tag({ children, variant = "default" }: { children: React.ReactNode; variant?: "violet" | "blue" | "green" | "default" }) {
  const styles = {
    violet: "bg-violet-50 border-violet-200 text-violet-700",
    blue: "bg-sky-50 border-sky-200 text-sky-700",
    green: "bg-green-50 border-green-200 text-green-700",
    default: "bg-slate-50 border-slate-200 text-slate-600",
  };
  return (
    <span className={cn("inline-flex items-center rounded-full border px-2.5 py-1 text-xs font-medium", styles[variant])}>
      {children}
    </span>
  );
}

// NOTE: For later implementation — computer-generated friendly age range string
// e.g. "Newborns to 5yr olds" or "12mth olds to 10yr olds"
function ageRangeToFriendly(minMonths: number, maxMonths: number): string {
  const minLabel = minMonths === 0 ? "Newborns" : minMonths < 12 ? `${minMonths}mth olds` : `${Math.floor(minMonths / 12)}yr olds`;
  const maxLabel = maxMonths < 12 ? `${maxMonths}mth olds` : `${Math.floor(maxMonths / 12)}yr olds`;
  return `${minLabel} to ${maxLabel}`;
}

function childrenCountLabel(count: number): string {
  if (count === 1) return "1 child";
  return `Up to ${count} children`;
}

const BADGE_ICONS: Record<string, React.ElementType> = {
  Clock, Baby, GraduationCap, Award, Car, Globe, Heart,
  Stethoscope, CigaretteOff, PawPrint, Users, ShieldCheck,
  Briefcase, BookOpen,
};

// ── Tab definitions ──────────────────────────────────────────────────────────

const PROFILE_TABS = [
  { id: "about" as const, label: "About" },
  { id: "experience" as const, label: "Experience" },
  { id: "availability" as const, label: "Availability" },
];

type ProfileTabId = (typeof PROFILE_TABS)[number]["id"];

// ══════════════════════════════════════════════════════════════════════════════
//  MAIN COMPONENT
// ══════════════════════════════════════════════════════════════════════════════

export function ProfileTestClient() {
  const [profileExpanded, setProfileExpanded] = useState(true);
  const [profileTab, setProfileTab] = useState<ProfileTabId>("about");
  const [photoViewerOpen, setPhotoViewerOpen] = useState(false);
  const [photoViewerIndex, setPhotoViewerIndex] = useState(0);

  const h = MOCK_HERO;

  // Build stat boxes — only non-zero values
  const statBoxes: { value: number; label: string }[] = [];
  if (MOCK_EXPERIENCE_STATS.total_experience_years > 0) {
    statBoxes.push({ value: MOCK_EXPERIENCE_STATS.total_experience_years, label: "Years Childcare" });
  }
  if (MOCK_EXPERIENCE_STATS.under_3_experience_years > 0) {
    statBoxes.push({ value: MOCK_EXPERIENCE_STATS.under_3_experience_years, label: "Years Under 3s" });
  }
  if (MOCK_EXPERIENCE_STATS.newborn_experience_years > 0) {
    statBoxes.push({ value: MOCK_EXPERIENCE_STATS.newborn_experience_years, label: "Years Newborns" });
  }

  return (
    <>
      {/* ═══════════════════════════════════════════════════════════════════
          HERO CARD
         ═══════════════════════════════════════════════════════════════════ */}
      <div className="relative rounded-2xl border border-slate-200 bg-white shadow-sm overflow-hidden">
        {h.isVerified && (
          <span className="absolute top-3 right-3 z-10 inline-flex items-center gap-1.5 rounded-full bg-green-50 border border-green-200 px-3 py-1 text-xs font-semibold text-green-700">
            <ShieldCheck className="h-3.5 w-3.5" /> Verified
          </span>
        )}
        <div className="h-12 bg-gradient-to-br from-violet-50 to-violet-100/50" />

        <div className="relative px-5 pb-5">
          <button className="absolute top-14 right-4 flex h-7 w-7 items-center justify-center rounded-lg text-slate-300 hover:text-violet-600 hover:bg-slate-50 transition-colors z-10">
            <Pencil className="h-3.5 w-3.5" />
          </button>
          <div className="flex items-end gap-4 -mt-10">
            <div className="relative shrink-0">
              <div className="relative h-32 w-32 overflow-hidden rounded-full border-4 border-white bg-violet-50 shadow-md">
                {h.profilePictureUrl ? (
                  <img src={h.profilePictureUrl} alt={`${h.firstName}'s photo`} className="h-full w-full object-cover" />
                ) : (
                  <div className="flex h-full w-full items-center justify-center text-3xl font-bold text-violet-300">
                    {h.firstName[0]}
                  </div>
                )}
              </div>
              {h.isVerified && (
                <div className="absolute bottom-2 right-0 flex h-7 w-7 items-center justify-center rounded-full bg-green-50 border border-green-200 ring-2 ring-white">
                  <ShieldCheck className="h-4 w-4 text-green-700" />
                </div>
              )}
            </div>

            <div className="flex-1 min-w-0 pb-1 pt-4">
              <h1 className="text-2xl font-bold text-slate-900">
                {h.firstName}{h.age ? `, ${h.age}` : ""}
              </h1>
              {/* Details block with photo fan absolutely positioned to the right */}
              <div className="relative mt-0.5">
                <div>
                  {MOCK_GOOD_TO_KNOW.nationality && (
                    <p className="flex items-center gap-1 text-sm text-slate-500 mt-0.5">
                      <Globe className="h-3.5 w-3.5" /> {MOCK_GOOD_TO_KNOW.nationality}
                    </p>
                  )}
                  {MOCK_GOOD_TO_KNOW.languages.length > 0 && (
                    <p className="flex items-center gap-1 text-xs text-slate-400 mt-0.5">
                      <Languages className="h-3 w-3" />
                      {MOCK_GOOD_TO_KNOW.other_languages
                        ? `${MOCK_GOOD_TO_KNOW.languages.join(", ")} + ${MOCK_GOOD_TO_KNOW.other_languages}`
                        : MOCK_GOOD_TO_KNOW.languages.join(", ")}
                    </p>
                  )}
                  <p className="flex items-center gap-1 text-sm text-slate-500 mt-0.5">
                    <MapPin className="h-3.5 w-3.5" /> {h.suburb}
                  </p>
                </div>

                {/* Additional photos — fanned stack, pinned to right, spans full height of details */}
                {h.additionalPhotoColors.length > 0 && (
                  <button
                    onClick={() => { setPhotoViewerIndex(0); setPhotoViewerOpen(true); }}
                    className="absolute top-0 right-0 bottom-0 w-16 cursor-pointer group mr-12"
                  >
                    {h.additionalPhotoColors.slice(0, 3).map((color, i) => {
                      const rotations = ["-rotate-[20deg]", "rotate-0", "rotate-[20deg]"];
                      const offsets = ["left-0", "left-3", "left-6"];
                      const zIndexes = ["z-[3]", "z-[2]", "z-[1]"];
                      return (
                        <div
                          key={i}
                          className={cn(
                            "absolute top-1/2 -translate-y-1/2 h-[85%] aspect-square overflow-hidden rounded-lg border-2 border-white shadow-md transition-transform group-hover:scale-105",
                            rotations[i], offsets[i], zIndexes[i], color,
                          )}
                        />
                      );
                    })}
                  </button>
                )}
              </div>
            </div>

          </div>

          {/* ai_content.headline */}
          {MOCK_AI_HEADLINE && (
            <p className="mt-3 text-sm text-slate-600 leading-relaxed">{MOCK_AI_HEADLINE}</p>
          )}

          {/* Trait badges */}
          {MOCK_BADGES.length > 0 && (
            <div className="mt-3 flex flex-wrap gap-1.5">
              {MOCK_BADGES.map((badge, i) => {
                const Icon = BADGE_ICONS[badge.icon] || Check;
                return (
                  <span key={i} className={cn(
                    "inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-medium",
                    badge.primary
                      ? "bg-violet-50 text-violet-700 border border-violet-200"
                      : "bg-slate-50 text-slate-600 border border-slate-200"
                  )}>
                    <Icon className="h-3 w-3" /> {badge.label}
                  </span>
                );
              })}
            </div>
          )}

          {/* Accordion toggle */}
          <div className="mt-4">
            <button
              type="button"
              onClick={() => setProfileExpanded((prev) => !prev)}
              className="flex w-full items-center justify-center gap-2 rounded-lg bg-violet-600 hover:bg-violet-700 px-4 py-2.5 text-white font-medium text-sm transition-colors h-10"
            >
              <User className="h-4 w-4" />
              Childcare Profile
              {profileExpanded ? <ChevronUp className="h-4 w-4 ml-1" /> : <ChevronDown className="h-4 w-4 ml-1" />}
            </button>
          </div>
        </div>
      </div>

      {/* ═══════════════════════════════════════════════════════════════════
          ACCORDION
         ═══════════════════════════════════════════════════════════════════ */}
      {profileExpanded && (
        <>
          <div className="flex gap-1 rounded-xl bg-slate-100 p-1">
            {PROFILE_TABS.map((tab) => (
              <button
                key={tab.id}
                onClick={() => setProfileTab(tab.id)}
                className={cn(
                  "flex-1 rounded-lg px-4 py-2 text-sm font-medium transition-all",
                  profileTab === tab.id
                    ? "bg-white text-slate-900 shadow-sm"
                    : "text-slate-500 hover:text-slate-700"
                )}
              >
                {tab.label}
              </button>
            ))}
          </div>

          {/* ══════════════════════════════════════════════════════════════
              ABOUT TAB — "Who I Am"
              Sections:
                1. About {Name} — ai_content.bio_summary.about + motivation
                2. Personality — ai_content.bio_summary.personality + traits tags
                3. My Values — ai_content.bio_summary.values + values tags
                4. What I Offer — ai_content.bio_summary.what_i_offer
                                  + role_types (selected only) + level_of_support
             ══════════════════════════════════════════════════════════════ */}
          {profileTab === "about" && (
            <div className="space-y-3">

              {/* 1. ai_content.bio_summary.intro + personality traits */}
              <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
                <div className="flex items-center gap-2 mb-3">
                  <Sparkles className="h-4 w-4 text-violet-400" />
                  <h3 className="text-sm font-semibold text-slate-900">About {h.firstName}</h3>
                </div>
                <div
                  className="text-sm text-slate-600 leading-relaxed [&_p]:mb-2 [&_p:last-child]:mb-0"
                  dangerouslySetInnerHTML={{ __html: MOCK_AI_ABOUT }}
                />
                {/* Motivation callout */}
                <div className="mt-3 flex items-center gap-2 rounded-lg bg-violet-50/50 border border-violet-100 px-3 py-2">
                  <Heart className="h-3.5 w-3.5 text-violet-400 shrink-0" />
                  <p className="text-xs text-violet-600">
                    <span className="font-medium">What drives me:</span> {MOCK_MOTIVATION}
                  </p>
                </div>
              </div>

              {/* 2. ai_content.bio_summary.personality + personality_traits tags */}
              <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
                <div className="flex items-center gap-2 mb-3">
                  <Smile className="h-4 w-4 text-violet-500" />
                  <h3 className="text-sm font-semibold text-slate-900">Personality</h3>
                </div>
                <div
                  className="text-sm text-slate-600 leading-relaxed mb-3 [&_p]:mb-2 [&_p:last-child]:mb-0"
                  dangerouslySetInnerHTML={{ __html: MOCK_AI_PERSONALITY }}
                />
                <div className="flex flex-wrap gap-1.5">
                  {MOCK_PERSONALITY_TRAITS.map((trait) => (
                    <Tag key={trait} variant="violet">{trait}</Tag>
                  ))}
                </div>
              </div>

              {/* 3. ai_content.bio_summary.values + professional_values tags */}
              <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
                <div className="flex items-center gap-2 mb-3">
                  <HandHeart className="h-4 w-4 text-violet-400" />
                  <h3 className="text-sm font-semibold text-slate-900">My Values</h3>
                </div>
                <div
                  className="text-sm text-slate-600 leading-relaxed mb-3 [&_p]:mb-2 [&_p:last-child]:mb-0"
                  dangerouslySetInnerHTML={{ __html: MOCK_AI_VALUES }}
                />
                <div className="flex flex-wrap gap-1.5">
                  {MOCK_PROFESSIONAL_VALUES.map((value) => (
                    <Tag key={value} variant="violet">{value}</Tag>
                  ))}
                </div>
              </div>

              {/* 4. ai_content.bio_summary.what_i_offer + selected role tags */}
              <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
                <div className="flex items-center gap-2 mb-3">
                  <Briefcase className="h-4 w-4 text-violet-400" />
                  <h3 className="text-sm font-semibold text-slate-900">What I Offer</h3>
                </div>
                <div
                  className="text-sm text-slate-600 leading-relaxed mb-3 [&_p]:mb-2 [&_p:last-child]:mb-0"
                  dangerouslySetInnerHTML={{ __html: MOCK_AI_WHAT_I_OFFER }}
                />
                <div className="flex flex-wrap gap-1.5">
                  {MOCK_PREFERENCES.role_types.map((tag) => (
                    <Tag key={tag} variant="violet">{tag}</Tag>
                  ))}
                  <Tag variant="violet">{MOCK_LEVEL_OF_SUPPORT}</Tag>
                </div>
              </div>

            </div>
          )}

          {/* ══════════════════════════════════════════════════════════════
              EXPERIENCE TAB — "Why Trust Me"
              Sections:
                1. Experience — ai_content.experience_summary + stat boxes
                2. Background — ai_content.bio_summary.background
                   + qualification (if any) + role history
                3. Safety & Assurance — AI text + WWCC (if level≥3) + cert badges
                4. Good to Know — comfortable with (age, children, needs)
                   + booleans (license, car, pets, etc.)
             ══════════════════════════════════════════════════════════════ */}
          {profileTab === "experience" && (
            <div className="space-y-3">

              {/* 1. ai_content.experience_summary + stats */}
              <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
                <div className="flex items-center gap-2 mb-3">
                  <Briefcase className="h-4 w-4 text-violet-400" />
                  <h3 className="text-sm font-semibold text-slate-900">Experience</h3>
                </div>
                <div
                  className="text-sm text-slate-600 leading-relaxed mb-4 [&_p]:mb-2 [&_p:last-child]:mb-0"
                  dangerouslySetInnerHTML={{ __html: MOCK_AI_EXPERIENCE }}
                />
                {statBoxes.length > 0 && (
                  <div className={cn(
                    "grid gap-2.5",
                    statBoxes.length === 1 && "grid-cols-1 max-w-[200px]",
                    statBoxes.length === 2 && "grid-cols-2",
                    statBoxes.length === 3 && "grid-cols-3",
                  )}>
                    {statBoxes.map((s) => (
                      <StatBox key={s.label} value={s.value} label={s.label} />
                    ))}
                  </div>
                )}
              </div>

              {/* 2. Background — AI text + qualification + role history */}
              <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
                <div className="flex items-center gap-2 mb-3">
                  <CalendarCheck className="h-4 w-4 text-violet-400" />
                  <h3 className="text-sm font-semibold text-slate-900">Background</h3>
                </div>
                <div
                  className="text-sm text-slate-600 leading-relaxed mb-4 [&_p]:mb-2 [&_p:last-child]:mb-0"
                  dangerouslySetInnerHTML={{ __html: MOCK_AI_BACKGROUND }}
                />
                {/* Qualification — only shown if they have one */}
                {MOCK_QUALIFICATIONS.highest_qualification && (
                  <div className="flex items-start gap-2.5 rounded-lg bg-violet-50 border border-violet-100 px-3 py-2.5 mb-3">
                    <GraduationCap className="h-4 w-4 text-violet-500 mt-0.5 shrink-0" />
                    <span className="text-sm font-medium text-violet-700">{MOCK_QUALIFICATIONS.highest_qualification}</span>
                  </div>
                )}
                {/* Role history */}
                {MOCK_CHILDCARE_ROLES.length > 0 && (
                  <div className="space-y-2">
                    {MOCK_CHILDCARE_ROLES.map((role) => (
                      <div key={role.role} className="flex items-center justify-between rounded-lg bg-slate-50 px-3 py-2.5">
                        <span className="text-sm font-medium text-slate-700">{role.role}</span>
                        <span className="text-xs text-slate-500">{role.duration} {role.duration === 1 ? "year" : "years"}</span>
                      </div>
                    ))}
                  </div>
                )}
              </div>

              {/* 3. Safety & Assurance — NOT ai-generated, computer-generated from structured data */}
              {/* Order: WWCC > First Aid in Childcare > First Aid > CPR > Child Protection > other > Vaccinated > Non-Smoker */}
              {(() => {
                const CERT_ORDER = [
                  "First Aid in Education & Care Setting",
                  "First Aid",
                  "CPR",
                  "Child Protection",
                ];
                const orderedCerts = CERT_ORDER.filter((c) => MOCK_QUALIFICATIONS.certificates.includes(c));
                const otherCerts = MOCK_QUALIFICATIONS.certificates.filter((c) => !CERT_ORDER.includes(c));
                const hasItems = MOCK_HERO.verificationLevel >= 3 || orderedCerts.length > 0 || otherCerts.length > 0 || MOCK_GOOD_TO_KNOW.vaccination_status || MOCK_GOOD_TO_KNOW.non_smoker;
                if (!hasItems) return null;
                return (
                  <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
                    <div className="flex items-center gap-2 mb-3">
                      <ShieldCheck className="h-4 w-4 text-violet-400" />
                      <h3 className="text-sm font-semibold text-slate-900">Safety & Assurance</h3>
                    </div>
                    <div className="grid grid-cols-2 gap-2">
                      {MOCK_HERO.verificationLevel >= 3 && (
                        <GlanceItem icon={ShieldCheck} label="WWCC" variant="green" />
                      )}
                      {orderedCerts.map((cert) => (
                        <GlanceItem key={cert} icon={Award} label={cert} variant="green" />
                      ))}
                      {otherCerts.map((cert) => (
                        <GlanceItem key={cert} icon={Award} label={cert} variant="green" />
                      ))}
                      {MOCK_GOOD_TO_KNOW.vaccination_status && (
                        <GlanceItem icon={Stethoscope} label="Fully Vaccinated" variant="green" />
                      )}
                      {MOCK_GOOD_TO_KNOW.non_smoker && (
                        <GlanceItem icon={CigaretteOff} label="Non-Smoker" variant="green" />
                      )}
                    </div>
                  </div>
                );
              })()}

              {/* 4. Good to Know — sectioned: best with, can support, additionally */}
              <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
                <div className="flex items-center gap-2 mb-4">
                  <ThumbsUp className="h-4 w-4 text-violet-400" />
                  <h3 className="text-sm font-semibold text-slate-900">Good to Know</h3>
                </div>

                {/* Best with supporting */}
                <h4 className="text-xs font-semibold text-slate-500 uppercase tracking-wide mb-2">Best with supporting</h4>
                <div className="grid grid-cols-2 gap-2 mb-4">
                  <GlanceItem icon={Baby} label={ageRangeToFriendly(MOCK_PREFERENCES.min_child_age_months, MOCK_PREFERENCES.max_child_age_months)} />
                  <GlanceItem icon={Users} label={childrenCountLabel(MOCK_PREFERENCES.max_children)} />
                </div>

                {/* Can support */}
                {(MOCK_PREFERENCES.additional_needs || MOCK_GOOD_TO_KNOW.comfortable_with_pets) && (
                  <>
                    <h4 className="text-xs font-semibold text-slate-500 uppercase tracking-wide mb-2">Can support</h4>
                    <div className="grid grid-cols-2 gap-2 mb-4">
                      {MOCK_PREFERENCES.additional_needs && (
                        <GlanceItem icon={Accessibility} label="Children with additional needs" />
                      )}
                      {MOCK_GOOD_TO_KNOW.comfortable_with_pets && (
                        <GlanceItem icon={PawPrint} label="Families with pets" />
                      )}
                    </div>
                  </>
                )}

                {/* Additionally */}
                {(MOCK_GOOD_TO_KNOW.drivers_license || MOCK_GOOD_TO_KNOW.has_car) && (
                  <>
                    <h4 className="text-xs font-semibold text-slate-500 uppercase tracking-wide mb-2">Additionally</h4>
                    <div className="grid grid-cols-2 gap-2">
                      {MOCK_GOOD_TO_KNOW.drivers_license && <GlanceItem icon={Car} label="I have my driver's license" />}
                      {MOCK_GOOD_TO_KNOW.has_car && <GlanceItem icon={Car} label="I have my own car" />}
                    </div>
                  </>
                )}
              </div>

            </div>
          )}

          {/* ══════════════════════════════════════════════════════════════
              AVAILABILITY TAB — unchanged
             ══════════════════════════════════════════════════════════════ */}
          {profileTab === "availability" && (
            <div className="space-y-3">
              <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
                <div className="flex items-center justify-between mb-4">
                  <div className="flex items-center gap-2">
                    <Clock className="h-4 w-4 text-violet-400" />
                    <h3 className="text-sm font-semibold text-slate-900">Availability</h3>
                  </div>
                  {MOCK_AVAILABILITY.immediate_start && (
                    <span className="inline-flex items-center gap-1.5 rounded-full bg-green-50 border border-green-200 px-2.5 py-1 text-xs font-medium text-green-700">
                      <CalendarCheck className="h-3 w-3" /> Can start immediately
                    </span>
                  )}
                </div>
                <AvailabilityGrid schedule={MOCK_AVAILABILITY.schedule} firstName={MOCK_HERO.firstName} />
              </div>
            </div>
          )}
        </>
      )}

      {/* Photo viewer modal */}
      {photoViewerOpen && h.additionalPhotos.length > 0 && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70" onClick={() => setPhotoViewerOpen(false)}>
          <div className="relative max-w-lg w-full mx-4" onClick={(e) => e.stopPropagation()}>
            <button
              onClick={() => setPhotoViewerOpen(false)}
              className="absolute -top-10 right-0 flex h-8 w-8 items-center justify-center rounded-full bg-white/20 text-white hover:bg-white/30 transition-colors"
            >
              <X className="h-5 w-5" />
            </button>
            <div className="relative overflow-hidden rounded-2xl bg-slate-900">
              <img
                src={h.additionalPhotos[photoViewerIndex]}
                alt={`${h.firstName}'s photo ${photoViewerIndex + 1}`}
                className="w-full aspect-[4/3] object-cover"
              />
              {h.additionalPhotos.length > 1 && (
                <>
                  <button
                    onClick={() => setPhotoViewerIndex((prev) => (prev - 1 + h.additionalPhotos.length) % h.additionalPhotos.length)}
                    className="absolute left-2 top-1/2 -translate-y-1/2 flex h-9 w-9 items-center justify-center rounded-full bg-black/40 text-white hover:bg-black/60 transition-colors"
                  >
                    <ChevronLeft className="h-5 w-5" />
                  </button>
                  <button
                    onClick={() => setPhotoViewerIndex((prev) => (prev + 1) % h.additionalPhotos.length)}
                    className="absolute right-2 top-1/2 -translate-y-1/2 flex h-9 w-9 items-center justify-center rounded-full bg-black/40 text-white hover:bg-black/60 transition-colors"
                  >
                    <ChevronRight className="h-5 w-5" />
                  </button>
                </>
              )}
            </div>
            <div className="flex justify-center gap-1.5 mt-3">
              {h.additionalPhotos.map((_, i) => (
                <button
                  key={i}
                  onClick={() => setPhotoViewerIndex(i)}
                  className={cn(
                    "h-2 w-2 rounded-full transition-colors",
                    i === photoViewerIndex ? "bg-white" : "bg-white/40"
                  )}
                />
              ))}
            </div>
          </div>
        </div>
      )}
    </>
  );
}

// ╔══════════════════════════════════════════════════════════════════════════════╗
// ║  DESIGN SPEC — Nanny Profile Layout (v1)                                   ║
// ║                                                                            ║
// ║  Reference for applying this layout to all profile views:                  ║
// ║    - NannyProfileView.tsx (public profile)                                 ║
// ║    - NannyMyProfile.tsx (nanny's own profile in hub)                       ║
// ║    - Parent browse cards (summary variant)                                 ║
// ╚══════════════════════════════════════════════════════════════════════════════╝
//
// ┌──────────────────────────────────────────────────────────────────────────────┐
// │  HERO CARD                                                                  │
// ├──────────────────────────────────────────────────────────────────────────────┤
// │                                                                             │
// │  Structure (top → bottom):                                                  │
// │    1. Violet gradient bar — h-12, from-violet-50 to-violet-100/50           │
// │    2. "Verified" badge — absolute top-3 right-3, green pill with            │
// │       ShieldCheck icon (only if isVerified)                                 │
// │    3. Profile picture — 128x128 (h-32 w-32), rounded-full, border-4        │
// │       border-white, bg-violet-50, shadow-md. Overlaps bar with -mt-10.     │
// │       - Shield icon: absolute bottom-2 right-0, green circle, ring-2       │
// │         ring-white (only if isVerified)                                     │
// │    4. Name + details block — to the right of profile pic (flex items-end)   │
// │       - Name: "{firstName}, {age}" — text-2xl font-bold text-slate-900     │
// │       - Details sub-block (relative, contains photo fan):                   │
// │         a. Nationality — Globe icon, text-sm text-slate-500                 │
// │         b. Language — Languages icon, text-xs text-slate-400                │
// │            Format: "English + {other_languages}" if multilingual            │
// │         c. Suburb — MapPin icon, text-sm text-slate-500                     │
// │         d. Photo fan — absolute right-0 mr-12, spans top-0 to bottom-0     │
// │            of the nationality→suburb block. See PHOTO FAN section.          │
// │    5. Edit button — absolute top-14 right-4, Pencil icon, only on nanny's  │
// │       own profile view. Not on public view.                                 │
// │    6. Tagline — ai_content.headline, text-sm text-slate-600, mt-3          │
// │       Full width below the name/details block.                              │
// │    7. Badge pills — mt-3, flex flex-wrap gap-1.5                            │
// │       - Experience stats (if > 0): violet pill with icon                    │
// │         "{X} yrs experience", "{X} yrs under 3s", "{X} yr newborns"        │
// │       - Qualification: slate pill (if they have one)                        │
// │       - NO certificates, car, or other badges on hero                       │
// │    8. Accordion button — "Childcare Profile", violet-600, full width        │
// │       mt-4, h-10, with User icon + chevron                                 │
// │                                                                             │
// │  NOT on hero card:                                                          │
// │    - Hourly rate (removed)                                                  │
// │    - Certificates, car, pets, etc. (moved to Experience tab)                │
// │                                                                             │
// ├──────────────────────────────────────────────────────────────────────────────┤
// │  PHOTO FAN                                                                  │
// ├──────────────────────────────────────────────────────────────────────────────┤
// │                                                                             │
// │  Up to 3 additional photos, displayed as a fanned card stack.               │
// │  Positioned absolutely within the nationality→suburb details block.         │
// │                                                                             │
// │  Container: absolute top-0 right-0 bottom-0 w-16 mr-12                     │
// │  Each card: absolute top-1/2 -translate-y-1/2, h-[85%] aspect-square       │
// │    rounded-lg border-2 border-white shadow-md                               │
// │                                                                             │
// │  Card layout (left = frontmost, like holding cards in hand):                │
// │    Card 1: -rotate-[20deg], left-0, z-[3] (front)                          │
// │    Card 2: rotate-0,        left-3, z-[2] (middle)                          │
// │    Card 3: rotate-[20deg],  left-6, z-[1] (back)                           │
// │                                                                             │
// │  Hover: group-hover:scale-105 on all cards.                                 │
// │  Click: opens photo viewer modal (lightbox with left/right nav + dots).     │
// │  If no photos: fan is hidden entirely.                                      │
// │                                                                             │
// ├──────────────────────────────────────────────────────────────────────────────┤
// │  TAB SWITCHER                                                               │
// ├──────────────────────────────────────────────────────────────────────────────┤
// │                                                                             │
// │  3 tabs: About | Experience | Availability                                  │
// │  Segmented control style: rounded-xl bg-slate-100 p-1                       │
// │  Active tab: bg-white text-slate-900 shadow-sm                              │
// │  Inactive: text-slate-500 hover:text-slate-700                              │
// │                                                                             │
// ├──────────────────────────────────────────────────────────────────────────────┤
// │  TILE STYLE (shared across all tabs)                                        │
// ├──────────────────────────────────────────────────────────────────────────────┤
// │                                                                             │
// │  Every content tile: rounded-2xl border border-slate-200 bg-white p-5       │
// │    shadow-sm                                                                │
// │  Tile header: icon (h-4 w-4 text-violet-400) + h3 (text-sm font-semibold   │
// │    text-slate-900), flex items-center gap-2 mb-3                            │
// │  AI text body: text-sm text-slate-600 leading-relaxed                       │
// │    [&_p]:mb-2 [&_p:last-child]:mb-0, rendered via dangerouslySetInnerHTML   │
// │  Tags below text: flex flex-wrap gap-1.5, Tag component with variant        │
// │  Spacing between tiles: space-y-3 on parent container                       │
// │                                                                             │
// ├──────────────────────────────────────────────────────────────────────────────┤
// │  ABOUT TAB — 4 tiles                                                        │
// ├──────────────────────────────────────────────────────────────────────────────┤
// │                                                                             │
// │  1. "About {Name}" — icon: Sparkles                                         │
// │     - AI text: ai_content.bio_summary.about (~40-50 words, 1st person)      │
// │     - Motivation callout below: violet-50/50 bg, border-violet-100,         │
// │       Heart icon, "What drives me: {motivation}"                            │
// │     - Data source: identity.motivation (single select)                      │
// │                                                                             │
// │  2. "Personality" — icon: Smile                                             │
// │     - AI text: ai_content.bio_summary.personality (~40-50 words)            │
// │     - Tags: personality_traits[] (5 selected), variant="violet"             │
// │     - Data source: identity.personality_traits                              │
// │                                                                             │
// │  3. "My Values" — icon: HandHeart                                           │
// │     - AI text: ai_content.bio_summary.values (~40-50 words)                 │
// │     - Tags: professional_values[] (5 selected), variant="violet"            │
// │     - Data source: identity.professional_values                             │
// │                                                                             │
// │  4. "What I Offer" — icon: Briefcase                                        │
// │     - AI text: ai_content.bio_summary.what_i_offer (~50-60 words)           │
// │     - Tags: role_types[] (selected only) + level_of_support,                │
// │       all variant="violet"                                                  │
// │     - Data sources: preferences.role_types, identity.level_of_support       │
// │                                                                             │
// ├──────────────────────────────────────────────────────────────────────────────┤
// │  EXPERIENCE TAB — 4 tiles                                                   │
// ├──────────────────────────────────────────────────────────────────────────────┤
// │                                                                             │
// │  1. "Experience" — icon: Briefcase                                          │
// │     - AI text: ai_content.experience_summary (~60-80 words)                 │
// │     - Stat boxes below: grid (1/2/3 cols based on count)                    │
// │       StatBox: rounded-xl bg-slate-50 p-3, violet number, slate label       │
// │       Only show stats where value > 0:                                      │
// │         "Years Childcare", "Years Under 3s", "Years Newborns"               │
// │     - Data sources: experience.total_experience_years,                      │
// │       under_3_experience_years, newborn_experience_years                    │
// │                                                                             │
// │  2. "Background" — icon: CalendarCheck                                      │
// │     - AI text: ai_content.bio_summary.background (~40-50 words)             │
// │     - Qualification callout (if any): violet-50 bg, GraduationCap icon,     │
// │       text-sm font-medium text-violet-700                                   │
// │     - Role history list: rounded-lg bg-slate-50 rows                        │
// │       Each: "{role}" left, "{duration} year(s)" right                       │
// │     - Data sources: nanny_credentials.highest_qualification,                │
// │       nanny_leads.experience.childcare_roles                                │
// │                                                                             │
// │  3. "Safety & Assurance" — icon: ShieldCheck                                │
// │     - NOT AI-generated — computer-generated from structured data            │
// │     - No descriptive text above items                                       │
// │     - 2-column grid of GlanceItem (variant="green")                         │
// │     - Fixed display order:                                                  │
// │       a. WWCC (if verification_level >= 3) — ShieldCheck icon               │
// │       b. First Aid in Education & Care Setting — Award icon                 │
// │       c. First Aid — Award icon                                             │
// │       d. CPR — Award icon                                                   │
// │       e. Child Protection — Award icon                                      │
// │       f. Any other certificates — Award icon                                │
// │       g. Fully Vaccinated — Stethoscope icon                                │
// │       h. Non-Smoker — CigaretteOff icon                                     │
// │     - Entire tile hidden if no items to show                                │
// │     - Data sources: verification_level, nanny_credentials.certificates,     │
// │       vaccination_status, non_smoker                                        │
// │                                                                             │
// │  4. "Good to Know" — icon: ThumbsUp                                         │
// │     - NOT AI-generated — computer-generated from structured data            │
// │     - 3 sub-sections with uppercase headers (hidden if section empty):      │
// │                                                                             │
// │     a. "BEST WITH SUPPORTING" — always shown                                │
// │        - Age range: Baby icon, ageRangeToFriendly() helper                  │
// │          Format: "Newborns to 5yr olds" / "12mth olds to 10yr olds"         │
// │        - Children count: Users icon, childrenCountLabel() helper            │
// │          Format: "1 child" or "Up to {n} children"                          │
// │                                                                             │
// │     b. "CAN SUPPORT" — only if additional_needs OR comfortable_with_pets    │
// │        - "Children with additional needs": Accessibility icon               │
// │        - "Families with pets": PawPrint icon                                │
// │                                                                             │
// │     c. "ADDITIONALLY" — only if drivers_license OR has_car                  │
// │        - "I have my driver's license": Car icon                             │
// │        - "I have my own car": Car icon                                      │
// │                                                                             │
// │     - All items use GlanceItem (variant="default" — slate bg)               │
// │     - Sub-headers: text-xs font-semibold text-slate-500 uppercase           │
// │       tracking-wide mb-2                                                    │
// │     - Items NOT in Good to Know (moved elsewhere):                          │
// │       nationality/language → hero card                                      │
// │       non-smoker → Safety & Assurance                                       │
// │       vaccinated → Safety & Assurance                                       │
// │                                                                             │
// ├──────────────────────────────────────────────────────────────────────────────┤
// │  AVAILABILITY TAB — 1 tile                                                  │
// ├──────────────────────────────────────────────────────────────────────────────┤
// │                                                                             │
// │  1. "Availability" — icon: Clock                                            │
// │     - Header row: title left, "Can start immediately" green pill right      │
// │       (CalendarCheck icon, only if immediate_start is true)                 │
// │     - 7-day x 4-slot grid table:                                            │
// │       Columns: Morning | Midday | Afternoon | Evening                       │
// │       Rows: Mon-Sun (abbreviated to 3 chars)                                │
// │       Available slot: bg-violet-500 text-white with Check icon              │
// │       Unavailable slot: bg-slate-50 text-slate-200 with "–"                 │
// │       Cell size: h-8 w-8 rounded-lg                                         │
// │     - No helper text below grid                                             │
// │     - No "looking for ongoing" tag                                          │
// │                                                                             │
// ├──────────────────────────────────────────────────────────────────────────────┤
// │  AI TONE GUIDE                                                              │
// ├──────────────────────────────────────────────────────────────────────────────┤
// │                                                                             │
// │  All AI-generated profile text must follow these rules:                     │
// │                                                                             │
// │  1. First-person "I" statements only                                        │
// │  2. Pattern: "I am {trait/value} so that you/your children {benefit}"       │
// │  3. The nanny speaks directly to the parent                                 │
// │  4. She owns her qualities and connects each to a concrete benefit          │
// │                                                                             │
// │  Good: "I'm patient and creative, so your children feel safe to explore"    │
// │  Bad:  "Your children will be in the hands of someone patient..."           │
// │                                                                             │
// │  AI-generated fields:                                                       │
// │    - ai_content.headline (~2-3 sentences, hero tagline)                     │
// │    - ai_content.bio_summary.about (~40-50 words)                            │
// │    - ai_content.bio_summary.personality (~40-50 words)                      │
// │    - ai_content.bio_summary.values (~40-50 words)                           │
// │    - ai_content.bio_summary.background (~40-50 words)                       │
// │    - ai_content.bio_summary.what_i_offer (~50-60 words)                     │
// │    - ai_content.experience_summary (~60-80 words)                           │
// │                                                                             │
// │  NOT AI-generated (computer-generated from structured data):                │
// │    - Safety & Assurance tile                                                │
// │    - Good to Know tile                                                      │
// │    - Availability grid                                                      │
// │    - Hero badge pills                                                       │
// │    - Photo fan                                                              │
// │                                                                             │
// ├──────────────────────────────────────────────────────────────────────────────┤
// │  REUSABLE COMPONENTS                                                        │
// ├──────────────────────────────────────────────────────────────────────────────┤
// │                                                                             │
// │  Tag — rounded pill with border                                             │
// │    Variants: "violet" | "blue" | "green" | "default"                        │
// │    violet: bg-violet-50 border-violet-200 text-violet-700                   │
// │    blue:   bg-sky-50 border-sky-200 text-sky-700                            │
// │    green:  bg-green-50 border-green-200 text-green-700                      │
// │    default: bg-slate-50 border-slate-200 text-slate-600                     │
// │    Size: rounded-full border px-2.5 py-1 text-xs font-medium               │
// │                                                                             │
// │  GlanceItem — icon + label row                                              │
// │    Variants: "default" | "green"                                            │
// │    default: bg-slate-50, icon text-violet-500, text text-slate-700          │
// │    green:   bg-green-50, icon text-green-600, text text-green-700           │
// │    Size: rounded-lg px-3 py-2.5, icon h-4 w-4, text text-sm               │
// │                                                                             │
// │  StatBox — numeric stat display                                             │
// │    rounded-xl bg-slate-50 p-3 text-center                                   │
// │    Value: text-xl font-bold text-violet-600                                 │
// │    Label: text-xs text-slate-500                                            │
// │                                                                             │
// │  AvailabilityGrid — 7x4 slot table                                          │
// │    See AVAILABILITY TAB section for full spec.                              │
// │                                                                             │
// ├──────────────────────────────────────────────────────────────────────────────┤
// │  DATA FIELD MAPPING (onboarding → ai_content JSONB)                         │
// ├──────────────────────────────────────────────────────────────────────────────┤
// │                                                                             │
// │  Onboarding Input                → ai_content JSONB Key                     │
// │  ─────────────────────────────────────────────────────────────────────────── │
// │  identity.motivation             → bio_summary.about (feeds AI prompt)      │
// │  identity.personality_traits     → bio_summary.personality (feeds AI)       │
// │  identity.professional_values    → bio_summary.values (feeds AI)            │
// │  identity.level_of_support       → displayed directly as Tag               │
// │  experience.total_experience     → experience_summary (feeds AI)            │
// │  experience.under_3_experience   → experience_summary (feeds AI)            │
// │  experience.newborn_experience   → experience_summary (feeds AI)            │
// │  experience.childcare_roles      → bio_summary.background (feeds AI)        │
// │  qualifications.highest_qual     → bio_summary.background (feeds AI)        │
// │  qualifications.certificates     → Safety tile (direct, not AI)             │
// │  preferences.role_types          → bio_summary.what_i_offer (feeds AI)      │
// │  preferences.min/max_age         → Good to Know (direct, not AI)            │
// │  preferences.max_children        → Good to Know (direct, not AI)            │
// │  preferences.additional_needs    → Good to Know (direct, not AI)            │
// │  matching booleans               → Good to Know / Safety (direct, not AI)   │
// │  nationality/languages           → Hero card (direct, not AI)               │
// │  verification_level              → Hero verified badge + WWCC in Safety     │
// │  nanny_images (up to 3)          → Hero photo fan (direct, not AI)          │
// │                                                                             │
// └──────────────────────────────────────────────────────────────────────────────┘
