import { describe, it, expect } from "vitest";
import {
  getRouteAllowlist,
  buildRouteAllowlistPrompt,
} from "./route-allowlist";

describe("route-allowlist — getRouteAllowlist", () => {
  it("loads pages from public/katie-manifest.json and partitions by audience", () => {
    const { nannyPaths, parentPaths, sharedPaths } = getRouteAllowlist();

    // Manifest is generated by scripts/generate-katie-manifest.mjs
    // during the build. Checking concrete known pages exist makes
    // the test fail loudly if the manifest format changes or if the
    // generator stops emitting page paths.
    expect(nannyPaths).toContain("/nanny");
    expect(nannyPaths).toContain("/nanny/profile");
    expect(parentPaths).toContain("/parent");
    expect(parentPaths.some((p) => p.startsWith("/parent/"))).toBe(true);

    // No path should be on more than one list.
    const overlap = nannyPaths.filter((p) => parentPaths.includes(p));
    expect(overlap).toEqual([]);
  });

  it("excludes API routes, admin, dev pages, framework internals", () => {
    const { nannyPaths, parentPaths, sharedPaths } = getRouteAllowlist();
    const all = [...nannyPaths, ...parentPaths, ...sharedPaths];
    for (const p of all) {
      expect(p.startsWith("/api/")).toBe(false);
      expect(p.startsWith("/admin")).toBe(false);
      expect(p.startsWith("/_next/")).toBe(false);
      expect(p.startsWith("/auth/")).toBe(false);
      expect(p).not.toBe("/nanny/profiletest");
      expect(p).not.toBe("/ui");
      expect(p).not.toBe("/ui2");
    }
  });

  it("renders dynamic Next.js segments as {brace} templates", () => {
    const { nannyPaths } = getRouteAllowlist();
    // The development hub uses [childId] in the file system.
    const developmentRoutes = nannyPaths.filter((p) =>
      p.includes("/development"),
    );
    expect(developmentRoutes.length).toBeGreaterThan(0);
    // None should still have square brackets.
    for (const p of developmentRoutes) {
      expect(p.includes("[")).toBe(false);
      expect(p.includes("]")).toBe(false);
    }
    // At least one should render as a template.
    expect(developmentRoutes.some((p) => p.includes("{childId}"))).toBe(true);
  });
});

describe("route-allowlist — buildRouteAllowlistPrompt", () => {
  it("includes nanny routes for nanny role; excludes parent-only paths", () => {
    const prompt = buildRouteAllowlistPrompt("nanny");
    expect(prompt).toContain("Valid URLs");
    expect(prompt).toContain("Do NOT invent paths");
    expect(prompt).toContain("/nanny/profile");
    expect(prompt).not.toContain("/parent/request");
  });

  it("includes parent routes for parent role; excludes nanny-only paths", () => {
    const prompt = buildRouteAllowlistPrompt("parent");
    expect(prompt).toContain("/parent");
    expect(prompt).not.toContain("/nanny/profile");
  });

  it("admin sees both audiences", () => {
    const prompt = buildRouteAllowlistPrompt("admin");
    expect(prompt).toContain("/nanny/profile");
    expect(prompt).toContain("/parent");
  });

  it("anti-hallucination rule is verbatim and references the existing capability list", () => {
    const prompt = buildRouteAllowlistPrompt("nanny");
    expect(prompt).toContain("support@babybloomsydney.com.au");
    expect(prompt).toContain("Do NOT invent");
    expect(prompt).toContain("NOT BUILT YET");
    // Cross-references the existing capability list rather than
    // duplicating it.
    expect(prompt).toContain("What You Can Do");
    expect(prompt).toContain("Not yet wired");
  });
});
