import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Privacy Policy | Baby Bloom',
};

export default function PrivacyPolicyPage() {
  return (
    <article>
      <header className="mb-8">
        <h1 className="text-2xl font-bold text-slate-900">Baby Bloom &mdash; Privacy Policy</h1>
        <p className="mt-2 text-sm text-slate-500">Version 1.0 | Last updated: 13 March 2026 | Effective date: 13 March 2026</p>
      </header>
      <div className="prose prose-sm prose-slate max-w-none prose-headings:text-base prose-headings:font-semibold prose-p:text-slate-600 prose-li:text-slate-600">

        <h2>1. About Baby Bloom</h2>
        <p>This Privacy Policy describes how Baby Bloom, Sydney (&ldquo;Baby Bloom&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;, &ldquo;our&rdquo;), ABN 17 463 812 867, collects, uses, discloses, and protects your personal information when you use the Baby Bloom platform (&ldquo;Platform&rdquo;).</p>
        <p>Baby Bloom is a digital facilitator and educational technology platform operating exclusively in New South Wales, Australia. We are bound by the Privacy Act 1988 (Cth) and the Australian Privacy Principles (APPs).</p>
        <p>If you have any questions about this Privacy Policy, contact us at <a href="mailto:contact@babybloomsydney.com.au">contact@babybloomsydney.com.au</a>.</p>

        <hr />

        <h2>2. What Personal Information We Collect</h2>
        <p>We collect the following categories of personal information:</p>
        <p><strong>Identity data:</strong> Your name, email address, phone number, residential address, date of birth, and suburb or postcode.</p>
        <p><strong>Children&apos;s data:</strong> Your children&apos;s names, ages, developmental milestones, special needs, allergies, medical conditions, and dietary requirements. This data is collected via registration forms and through the EdTech SaaS tools.</p>
        <p><strong>Verification data:</strong> Passport or government-issued ID scans, Working With Children Check (WWCC) card images, and selfie photographs. This data is collected from Childcare Professionals during the identity verification process.</p>
        <p><strong>Biometric data:</strong> Facial geometry extracted from selfie photographs for the purpose of identity matching against uploaded ID documents. This is classified as &ldquo;sensitive information&rdquo; under the Privacy Act 1988. See Section 5 for details.</p>
        <p><strong>Profile data:</strong> AI-generated professional bios, listed qualifications, experience, and uploaded profile photographs (Childcare Professionals only).</p>
        <p><strong>Usage data:</strong> Platform activity, booking history, match history, and connection records.</p>
        <p><strong>Communication data:</strong> Messages sent through the Platform, form submissions, and incident reports.</p>
        <p><strong>Facebook screenshots:</strong> Screenshots uploaded by Childcare Professionals for babysitting feature verification. See Section 10 for retention details.</p>
        <p><strong>Cookie data:</strong> Information collected through essential, analytics, and marketing cookies. See Section 15 and our <Link href="/legal/cookies">Cookie Policy</Link> for details.</p>

        <hr />

        <h2>3. How We Collect Personal Information</h2>
        <p>We collect personal information:</p>
        <p><strong>Directly from you:</strong> When you create an account, complete registration forms, build a profile, upload documents for verification, submit forms, send messages, or contact our support team.</p>
        <p><strong>Generated by AI:</strong> When our AI tools generate professional bios, developmental insights, activity suggestions, or assist in identity verification decisions.</p>
        <p><strong>From third-party databases:</strong> When we verify your Working With Children Check against the relevant NSW government database, or verify your identity through the Document Verification Service (DVS).</p>
        <p><strong>Automatically:</strong> Through cookies and analytics tools when you browse our website. See Section 15 and our <Link href="/legal/cookies">Cookie Policy</Link>.</p>

        <hr />

        <h2>4. Why We Collect Personal Information</h2>
        <p>We collect and use each category of personal information for specific, legitimate purposes:</p>
        <p><strong>Identity data:</strong> To create and manage your account, verify your identity, facilitate connections, send legal documents, and communicate with you about the Platform.</p>
        <p><strong>Children&apos;s data:</strong> Solely for the purpose of providing the EdTech SaaS developmental tools (activity suggestions, milestone logging, developmental insights). Children&apos;s data is <strong>never</strong> used for marketing purposes.</p>
        <p><strong>Verification data:</strong> To verify the identity and WWCC status of Childcare Professionals, and to maintain audit trails of verification decisions.</p>
        <p><strong>Biometric data:</strong> To confirm that the person creating a Professional account is the same person shown on their identity document. See Section 5.</p>
        <p><strong>Profile data:</strong> To display Professional profiles to Clients for the purpose of facilitating matchmaking and babysitting connections.</p>
        <p><strong>Usage data:</strong> To operate and improve the Platform, and to notify you of material changes to your status.</p>
        <p><strong>Communication data:</strong> To facilitate communication between users, process incident reports, and provide support.</p>
        <p>We only use your personal information for the purpose for which it was collected, or a directly related purpose, in accordance with APP 6.</p>

        <hr />

        <h2>5. Sensitive Information</h2>
        <p>The Privacy Act 1988 classifies biometric information as &ldquo;sensitive information&rdquo; under section 6(1). Australian Privacy Principle 3.3 requires that sensitive information can only be collected with the individual&apos;s informed, specific consent.</p>
        <p><strong>Biometric data:</strong> During the Childcare Professional verification process, we extract facial geometry from a selfie photograph and compare it to an uploaded identity document using AI facial recognition. Consent for this processing is obtained through a standalone <strong><Link href="/legal/biometric-notice">Biometric Data Collection Notice</Link></strong>, which is presented separately from and in addition to general Terms of Service acceptance.</p>
        <p>The Biometric Data Collection Notice explains:</p>
        <ul>
          <li>What biometric data are we collecting? (selfie photograph and facial geometry)</li>
          <li>Why? (to confirm identity document ownership)</li>
          <li>Who processes this data? (OpenAI GPT-4o, processing location: United States)</li>
          <li>How long is it retained? (for the life of your active account; deleted 90 days after account closure)</li>
          <li>What are your rights? (right to request deletion; right to refuse biometric processing and use alternative verification methods)</li>
          <li>Explicit consent checkbox: You must tick the consent box to proceed with biometric verification.</li>
        </ul>
        <p><strong>Your right to refuse biometric data:</strong> You may refuse to provide biometric data, which will prevent you from registering as a Professional via facial recognition, but you can still register as a Client or use alternative Professional verification methods.</p>
        <p><strong>Children&apos;s health and medical data:</strong> Information about children&apos;s medical conditions, allergies, special needs, and dietary requirements is also sensitive. This data is collected only with the Legal Guardian&apos;s explicit, specific consent obtained through a standalone <strong>Children&apos;s Sensitive Information Consent Form</strong> presented at the time of Hire confirmation (not embedded in general Terms).</p>
        <p>The Consent Form explains:</p>
        <ul>
          <li>What sensitive information is being collected? (medical conditions, allergies, dietary requirements, special needs, medications, emergency procedures)</li>
          <li>Why? (to ensure your child receives safe, appropriate care)</li>
          <li>Who processes this data? (Baby Bloom staff and the matched Childcare Professional)</li>
          <li>How long will it be kept? (during the care arrangement plus 90 days after arrangement ends or account closes)</li>
          <li>What are your rights? (right to access, correct, or delete; right to consent to specific categories only)</li>
          <li>Explicit consent checkboxes: You must tick to consent to each category of sensitive information you wish to disclose.</li>
        </ul>
        <p>Parents consent to specific categories of information, not all-or-nothing.</p>

        <hr />

        <h2>6. Children&apos;s Data Minimisation</h2>
        <p>In accordance with APP 3, we collect and share only the minimum personal information necessary for each purpose.</p>
        <p>When a Client posts a babysitting request, the broadcast sent to potential Childcare Professionals includes only the number of children and their age ranges. Detailed information about special needs, medical conditions, allergies, and dietary requirements is shared only with the Childcare Professional who is matched and approved for the specific booking.</p>

        <hr />

        <h2>7. AI Data Processing</h2>

        <h3>7.1 EdTech AI</h3>
        <p>Baby Bloom uses third-party AI providers (including but not limited to Google Gemini and Anthropic Claude) to power the EdTech SaaS tools. These tools process children&apos;s developmental milestones and activity history to generate activity suggestions, lesson plans, and developmental insights.</p>
        <p>Baby Bloom retains only the right to use genuinely anonymised, aggregated data to improve its AI models. &ldquo;Anonymised&rdquo; means that no individual child can be re-identified from the data used, in accordance with the Office of the Australian Information Commissioner&apos;s (OAIC) guidance on de-identification.</p>

        <h3>7.2 Verification AI</h3>
        <p>Baby Bloom uses a third-party AI provider (currently OpenAI GPT-4o) to assist in identity verification, including passport and ID document reading, selfie-to-ID facial matching, and WWCC card image extraction.</p>
        <p>AI-assisted verification is one layer of a multi-step process. AI is <strong>not</strong> the sole decision-maker. Cases flagged by the AI undergo human review by authorised Baby Bloom staff. Baby Bloom maintains audit trails of all AI-assisted verification decisions, recording the date, outcome, and basis for each decision.</p>

        <hr />

        <h2>8. Disclosure of Personal Information</h2>
        <p>We may disclose your personal information to:</p>
        <p><strong>The other party in a Connection:</strong> Upon a Connection being made (and with your explicit, per-connection consent), contact information is shared as follows:</p>
        <p><strong>Matchmaking Connections:</strong></p>
        <ul>
          <li>Professional&apos;s phone number is shared with the Client immediately after the Professional has consented through the Connection Agreement</li>
          <li>Client&apos;s phone number is NOT shared with the Professional; the Professional initiates contact using the phone number provided by the Client</li>
          <li>No address information is shared</li>
        </ul>
        <p><strong>Babysitting Connections:</strong></p>
        <ul>
          <li>Professional&apos;s phone number is shared with the Client upon booking confirmation</li>
          <li>Client&apos;s home address is shared with the Professional immediately after the Client has consented through the Connection Agreement</li>
          <li>Professional&apos;s address is NOT shared with the Client</li>
          <li>Only children&apos;s ages are shared during the babysitting request broadcast; detailed information (medical conditions, allergies, special needs) is shared only after the Professional is matched and has consented</li>
        </ul>
        <p><strong>Timing:</strong> All data sharing occurs immediately after the respective party has provided explicit consent through the applicable Connection Agreement. Both parties receive notification of the data that has been shared.</p>
        <p><strong>Third-party data processors:</strong> We share personal data with service providers who process data on our behalf. See Section 9.</p>
        <p><strong>Government bodies:</strong> We may disclose information to the NSW WWCC registry, the Document Verification Service, the NSW Department of Communities and Justice (for mandatory reporting), the eSafety Commissioner, or law enforcement agencies where required or authorised by law.</p>
        <p><strong>Authorised Baby Bloom staff:</strong> Your personal information may be accessed by authorised Baby Bloom staff for the purposes of platform operations, verification review, support, and incident management. Staff access is subject to internal access controls and all sensitive actions are logged.</p>

        <hr />

        <h2>9. Third-Party Data Processors</h2>
        <p>We share personal data with the following third-party processors under signed Data Processing Agreements in accordance with APP 8:</p>

        <p><strong>Supabase</strong> (Supabase Inc.)</p>
        <ul>
          <li>Function: Database and file storage</li>
          <li>Data shared: all user data including identity documents, biometric data, and children&apos;s data</li>
          <li>Processing location: Tokyo, Japan (AWS ap-northeast-1)</li>
          <li><strong>APP 8 Compliance Basis</strong>: Under Australian Privacy Principle (APP) 8, overseas disclosure of personal information is permitted if Baby Bloom takes <strong>reasonable steps</strong> to ensure the overseas recipient complies with the APPs. <strong>Important</strong>: Japan has not been prescribed as an adequate country under APP 8.3. Baby Bloom relies on APP 8.1 &ldquo;reasonable steps&rdquo; which include: (a) Executed Data Processing Agreement, (b) Due diligence assessment of Supabase&apos;s privacy and security practices, (c) Contractual commitments to APP compliance, and (d) Audit rights to verify compliance.</li>
          <li><strong>Data Residency Risk</strong>: Your personal information is processed in Japan under Japanese law. While Baby Bloom has taken steps to protect your data, Japanese privacy laws may differ from Australian law. You should be aware that data processed overseas may be subject to different legal frameworks and government access requests.</li>
          <li><strong>DPA Status</strong>: Pending execution via PandaDoc &mdash; <strong>must be completed before launch</strong></li>
          <li>DPA link: <a href="https://supabase.com/legal/dpa" target="_blank" rel="noopener noreferrer">https://supabase.com/legal/dpa</a></li>
        </ul>

        <p><strong>OpenAI</strong> (OpenAI, L.L.C.)</p>
        <ul>
          <li>Function: AI processing for verification pipeline and EdTech features</li>
          <li>Data shared: verification images (passport, ID, selfie, WWCC card), children&apos;s developmental data, profile text for bio generation</li>
          <li>Processing location: United States</li>
          <li>Data Retention: OpenAI retains API request data for 30 days and may use de-identified data to improve models. Training data is not used unless you explicitly opt in. See OpenAI&apos;s privacy policy at <a href="https://openai.com/privacy" target="_blank" rel="noopener noreferrer">https://openai.com/privacy</a></li>
          <li>US Government Access Risk: Data processed in the United States may be subject to US laws allowing government access (e.g., under the Electronic Communications Privacy Act). Baby Bloom has obtained OpenAI&apos;s EU Data Processing Addendum which provides data protection assurances.</li>
          <li><strong>DPA Status</strong>: Pending execution &mdash; <strong>must be completed before launch</strong></li>
          <li>DPA link: <a href="https://openai.com/policies/data-processing-addendum" target="_blank" rel="noopener noreferrer">https://openai.com/policies/data-processing-addendum</a></li>
        </ul>

        <p><strong>Anthropic</strong> (Anthropic, PBC)</p>
        <ul>
          <li>Function: AI processing for verification pipeline and EdTech features</li>
          <li>Data shared: verification images, children&apos;s developmental data, profile text for bio generation</li>
          <li>Processing location: United States</li>
          <li>Data Retention: Anthropic does not retain training copies of API requests. See Anthropic&apos;s privacy policy at <a href="https://www.anthropic.com/privacy" target="_blank" rel="noopener noreferrer">https://www.anthropic.com/privacy</a></li>
          <li><strong>DPA Status</strong>: Automatically incorporated into Anthropic&apos;s Commercial Terms of Service upon API usage</li>
          <li>DPA link: <a href="https://www.anthropic.com/terms" target="_blank" rel="noopener noreferrer">https://www.anthropic.com/terms</a></li>
        </ul>

        <p><strong>Resend</strong> (Plus Five Five, Inc.)</p>
        <ul>
          <li>Function: Email delivery</li>
          <li>Data shared: email addresses and email content (including Hire PDFs as attachments)</li>
          <li>Processing location: United States</li>
          <li><strong>DPA Status</strong>: Pending execution via dashboard &mdash; <strong>must be completed before launch</strong></li>
          <li>DPA link: <a href="https://resend.com/legal/dpa" target="_blank" rel="noopener noreferrer">https://resend.com/legal/dpa</a></li>
        </ul>

        <p><strong>Stripe</strong> (Stripe Payments Australia Pty Ltd)</p>
        <ul>
          <li>Function: Payment processing (SaaS subscription billing, refunds, chargebacks)</li>
          <li>Data shared: cardholder name, card number (tokenised &mdash; Baby Bloom never stores raw card numbers), billing address, email address, transaction amounts, transaction history, IP address, device fingerprint (for fraud detection)</li>
          <li>Processing location: Australia (primary, via Stripe&apos;s Australian entity) and United States (Stripe Inc., for fraud detection, analytics, and backup processing)</li>
          <li><strong>PCI DSS Compliance</strong>: Stripe is a certified PCI DSS Level 1 Service Provider &mdash; the highest level of payment security certification. Baby Bloom does not store, process, or transmit raw card numbers; all card data is tokenised by Stripe before reaching Baby Bloom&apos;s systems.</li>
          <li><strong>Data Baby Bloom receives from Stripe</strong>: Baby Bloom receives only: (a) a payment token (not the full card number), (b) last four digits of the card, (c) card brand (Visa, Mastercard, etc.), (d) transaction status (success/failure), (e) transaction amount, and (f) billing postcode. Baby Bloom does NOT receive or store your full card number, CVV, or expiry date.</li>
          <li><strong>APP 8 Compliance Basis</strong>: Stripe Payments Australia Pty Ltd processes Australian payments within Australia. For fraud detection and backup processing routed through Stripe Inc. (United States), Baby Bloom relies on APP 8.1 &ldquo;reasonable steps&rdquo; including the executed DPA, Stripe&apos;s Binding Corporate Rules, and PCI DSS Level 1 certification.</li>
          <li><strong>DPA Status</strong>: Pending execution &mdash; <strong>must be completed before launch</strong></li>
          <li>DPA link: <a href="https://stripe.com/au/legal/dpa" target="_blank" rel="noopener noreferrer">https://stripe.com/au/legal/dpa</a></li>
        </ul>

        <p><strong>International Data Transfers and APP 8 Compliance:</strong></p>
        <p>Your personal information may be processed overseas by the providers listed above. In accordance with APP 8, we take reasonable steps to ensure that overseas recipients handle your personal information in compliance with the Australian Privacy Principles. These steps include:</p>
        <ul>
          <li>Executed Data Processing Agreements with each overseas processor</li>
          <li>Due diligence assessment of each processor&apos;s privacy and security practices</li>
          <li>Contractual commitments to APP compliance as a condition of data sharing</li>
          <li>Audit rights to verify processor compliance</li>
        </ul>
        <p><strong>Risks of International Data Transfer:</strong></p>
        <p>You should be aware that data processed overseas may be subject to different privacy laws and potentially government access requests. We mitigate these risks through the measures listed above, but you accept the residual risk of overseas processing by using the Platform.</p>

        <hr />

        <h2>10. Data Retention</h2>
        <p>We retain personal information for the following periods:</p>
        <p><strong>Identity documents</strong> (passport scans, WWCC card images, selfie photographs): Retained for the life of your active account. Deleted 90 days after account closure.</p>
        <p><strong>Children&apos;s data</strong> (developmental logs, medical information, special needs): Retained for the life of your active account. Deleted 90 days after account closure.</p>
        <p><strong>Biometric data</strong> (facial geometry):</p>
        <ul>
          <li>Extracted facial geometry is retained on Baby Bloom&apos;s secure systems for the life of your active account</li>
          <li>The original selfie photograph is deleted immediately after facial geometry is extracted and verified (typically within 24 hours)</li>
          <li>Both facial geometry and the original photograph are deleted 90 days after account closure</li>
          <li>Facial geometry is stored in a separate, encrypted database with restricted access</li>
          <li>You may request deletion of biometric data at any time by contacting <a href="mailto:contact@babybloomsydney.com.au">contact@babybloomsydney.com.au</a>, except where retention is required by law</li>
        </ul>
        <p><strong>Form snapshots</strong> (connection forms, job posts): Retained for the life of your active account. Deleted 90 days after account closure.</p>
        <p><strong>Facebook verification screenshots:</strong></p>
        <ul>
          <li>Screenshots are retained only while verification is in progress (typically 1-2 business days)</li>
          <li>Baby Bloom does not retain copies after verification is confirmed; screenshots are automatically deleted</li>
          <li>Professionals uploading screenshots must redact other users&apos; identifying information before uploading (see Professional ToS Section 9.2)</li>
          <li>If a screenshot contains unredacted data of other Facebook users, Baby Bloom will request that the Professional re-submit a redacted version or use alternative verification method (e.g., referral code), and the unredacted screenshot will be deleted within 24 hours</li>
          <li>Baby Bloom does not use screenshots for any purpose other than verification and does not analyze or store data from other Facebook users who are not Baby Bloom users</li>
        </ul>
        <p><strong>Verification audit trail</strong> (pass/fail result, date of verification, document type verified): Retained permanently in de-identified form. De-identified means that no personally identifiable information (names, dates of birth, document numbers) is retained &mdash; only the verification outcome and date. This data is used to track verification quality and may be disclosed to the OAIC for regulatory oversight.</p>
        <p><strong>Payment data:</strong></p>
        <ul>
          <li>Baby Bloom does not store your full card number, CVV, or expiry date. These are held exclusively by Stripe and never touch Baby Bloom&apos;s servers.</li>
          <li>Baby Bloom retains: payment token, last four digits of card, card brand, transaction amounts, transaction dates, billing postcode, and refund/chargeback records.</li>
          <li>Transaction records are retained for <strong>7 years</strong> after the transaction date, as required by the Tax Administration Act 1953 (Cth) and the Income Tax Assessment Act 1997 (Cth) for financial record-keeping.</li>
          <li>If you close your account, payment records are retained for the remainder of the 7-year period (not deleted at 90 days like other data categories).</li>
          <li>You may request a copy of your payment history at any time by contacting <a href="mailto:compliance@babybloomsydney.com.au">compliance@babybloomsydney.com.au</a>.</li>
        </ul>
        <p><strong>Cookie data:</strong> Retained per the expiry period of each cookie. See our <Link href="/legal/cookies">Cookie Policy</Link>.</p>
        <p><strong>Why a 90-Day Grace Period?</strong></p>
        <p>The 90-day post-closure grace period exists to:</p>
        <ul>
          <li>Allow time for dispute resolution (e.g., if there is a disagreement about payment or service)</li>
          <li>Comply with record-keeping requirements under tax and employment law</li>
          <li>Respond to regulatory requests (e.g., if a complaint is lodged with NSW Fair Trading, the Fair Work Commission, or the OAIC)</li>
        </ul>
        <p>After 90 days, all personal information is permanently deleted, except for:</p>
        <ul>
          <li>De-identified verification audit trails (date, outcome, document type) retained permanently</li>
          <li>Data required by law to be retained (e.g., tax records for 5 years, if applicable)</li>
        </ul>
        <p><strong>Request for Expedited Deletion:</strong></p>
        <p>If you wish to request deletion of your data before the 90-day period ends, contact <a href="mailto:contact@babybloomsydney.com.au">contact@babybloomsydney.com.au</a>. We will review your request and may grant expedited deletion if there is no legal reason to retain the data.</p>

        <hr />

        <h2>11. Data Security</h2>
        <p>In accordance with APP 11, we take reasonable steps to protect your personal information from misuse, interference, loss, unauthorised access, modification, and disclosure. These steps include:</p>
        <ul>
          <li>Encryption of data at rest and in transit;</li>
          <li>Role-based access controls for Baby Bloom staff;</li>
          <li>Logging of all sensitive admin actions with timestamps and the identity of the staff member;</li>
          <li>Appropriate screening of staff members who have access to children&apos;s data and identity documents; and</li>
          <li>Regular review of security measures.</li>
        </ul>

        <hr />

        <h2>12. Access, Correction &amp; Deletion</h2>
        <p>In accordance with APPs 12 and 13, you have the right to:</p>
        <p><strong>Access:</strong> Request access to the personal information we hold about you.</p>
        <p><strong>Correction:</strong> Request correction of any personal information that is inaccurate, out of date, incomplete, irrelevant, or misleading.</p>
        <p><strong>Deletion:</strong> Request deletion of your personal information, subject to our retention obligations and any applicable legal requirements.</p>
        <p><strong>Data export:</strong> Before closing your account, you may request an export of your data (including children&apos;s developmental logs and activity history).</p>
        <p>To make a request, contact us at <a href="mailto:contact@babybloomsydney.com.au">contact@babybloomsydney.com.au</a>.</p>
        <p><strong>Access requests:</strong> We will provide access to your personal information within 10 business days. If we are unable to provide access within this timeframe, we will notify you and provide an expected completion date.</p>
        <p><strong>Correction requests:</strong> If you request correction and we refuse, we will provide written reasons. You may request that a statement of the refusal be attached to the record.</p>
        <p><strong>Deletion requests:</strong> We will review your deletion request and respond within 10 business days. We may refuse deletion if the data is required by law to be retained.</p>

        <hr />

        <h2>13. Notifiable Data Breaches</h2>
        <p>Baby Bloom complies with the Notifiable Data Breaches scheme under Part IIIC of the Privacy Act 1988. A data breach is &ldquo;notifiable&rdquo; if it is likely to result in serious harm (e.g., identity theft, financial loss, psychological harm, compromise of sensitive information).</p>
        <p>If we become aware of a notifiable data breach, we will:</p>
        <ol>
          <li>Assess whether the breach is likely to result in serious harm</li>
          <li>Notify affected individuals and the Office of the Australian Information Commissioner (OAIC) within 30 days</li>
          <li>Provide information about the breach, the data affected, and steps individuals should take to protect themselves</li>
          <li>Document the breach and our response for audit purposes</li>
        </ol>
        <p>We also maintain a Data Breach Response Plan, available upon request, which details our procedures for detecting, investigating, and responding to data breaches.</p>

        <hr />

        <h2>14. Consumer Data Right</h2>
        <p>Baby Bloom does not currently collect or process financial data that triggers obligations under the Consumer Data Right (CDR) framework. If we introduce payment processing, payroll, or other financial data features in the future, CDR compliance will be assessed and implemented before those features are launched.</p>

        <hr />

        <h2>15. Cookies</h2>
        <p>Our website uses cookies and similar tracking technologies. For full details of the cookies we use, how to manage your preferences, and how to decline non-essential cookies, please see our <Link href="/legal/cookies">Cookie Policy</Link>.</p>
        <p>In summary, we use:</p>
        <ul>
          <li><strong>Essential cookies</strong> for session management and security;</li>
          <li><strong>Analytics cookies</strong> (such as Google Analytics) to understand how visitors use our website; and</li>
          <li><strong>Marketing cookies</strong> (such as Meta Pixel) to support our community outreach.</li>
        </ul>

        <hr />

        <h2>16. Complaints</h2>
        <p>If you believe we have breached the Australian Privacy Principles or mishandled your personal information, you may lodge a complaint with us at <a href="mailto:compliance@babybloomsydney.com.au">compliance@babybloomsydney.com.au</a>. Please include:</p>
        <ul>
          <li>A detailed description of the issue</li>
          <li>The date(s) the issue occurred</li>
          <li>Any supporting documents</li>
        </ul>
        <p><strong>Our Response:</strong></p>
        <ul>
          <li>We will acknowledge receipt of your complaint within 5 business days and provide you with a reference number</li>
          <li>We will investigate the complaint and provide a substantive response within 30 days, or sooner if possible</li>
          <li>If investigation requires more than 30 days, we will provide you with an interim update explaining the delay and expected resolution date</li>
          <li>Our response will include the outcome of the investigation and any corrective action taken</li>
        </ul>
        <p><strong>External Complaint:</strong></p>
        <p>If you are not satisfied with our response within 30 days, or if we do not respond within 30 days, you may lodge a complaint with the Office of the Australian Information Commissioner (OAIC) at <a href="https://www.oaic.gov.au" target="_blank" rel="noopener noreferrer">www.oaic.gov.au</a> or by calling 1300 363 992.</p>

        <hr />

        <h2>17. Automated Decision-Making</h2>
        <p>Baby Bloom uses artificial intelligence and algorithms in ways that may result in automated decisions affecting you. You have rights under the Privacy Act in relation to these decisions.</p>
        <p><strong>17.1 AI-Assisted Verification</strong>: Baby Bloom uses artificial intelligence (OpenAI GPT-4o) to assist in verifying Professional identity and WWCC status. AI makes a preliminary decision, but all decisions affecting access to the Platform are subject to human review by authorized Baby Bloom staff before being finalized. You have the right to request explanation of any negative verification decision.</p>
        <p><strong>17.2 Algorithmic Matching</strong>: The Platform uses an algorithm to match Professionals with Client requests based on availability, location, preferences, and other factors. This is an automated decision that determines which Professionals are shown to Clients. You may request explanation of why you were or were not matched to a particular request.</p>
        <p><strong>17.3 EdTech Insights</strong>: The EdTech tools use AI to analyze your children&apos;s developmental milestones and generate personalized activity suggestions and developmental insights. These are automated recommendations, not diagnoses, and should not be relied upon as professional medical or developmental advice.</p>
        <p><strong>17.4 Right to Explanation</strong>: If you believe an automated decision has been made about you (e.g., matching algorithm, verification decision, content recommendation), you may request explanation by emailing <a href="mailto:contact@babybloomsydney.com.au">contact@babybloomsydney.com.au</a>. We will provide explanation within 10 business days.</p>
        <p><strong>17.5 Right to Human Review</strong>: You may request that a human review any automated decision and make a final determination. Human review is not a challenge to the automated decision but a right to have a qualified staff member consider your case.</p>
        <p><strong>17.6 Right to Opt-Out</strong>: If you do not wish to participate in algorithmic matching, you may request manual matching, which is subject to availability.</p>

        <hr />

        <h2>18. Organizational Reportable Conduct Obligations</h2>
        <p>Baby Bloom acknowledges that under the Children&apos;s Guardian Act 2019 (NSW), organizations providing services to children must have systems to identify and respond to <strong>reportable conduct</strong> (conduct that could constitute a criminal offense, abuse, ill-treatment, psychological harm, grooming, or sexual misconduct involving children).</p>
        <p>Baby Bloom&apos;s Head of Entity is required to:</p>
        <ul>
          <li>Establish systems to identify and manage reportable conduct</li>
          <li>Notify the Office of Children&apos;s Guardian within 7 business days of becoming aware of an allegation of reportable conduct</li>
          <li>Cooperate with any investigation by the Office of Children&apos;s Guardian</li>
          <li>Implement preventive measures and training</li>
        </ul>
        <p>If you report to Baby Bloom a concern that a Childcare Professional may have engaged in reportable conduct (e.g., inappropriate touching, grooming, abuse), Baby Bloom will assess the allegation and notify the Office of Children&apos;s Guardian as required by law. This is a separate legal obligation from your personal mandatory reporting obligation (s.27) and does not replace your requirement to report directly to the Child Protection Helpline on 132 111.</p>

        <hr />

        <h2>19. Children&apos;s Online Privacy Code Readiness</h2>
        <p>Baby Bloom acknowledges that the Office of the Australian Information Commissioner (OAIC) is developing a Children&apos;s Online Privacy Code (expected implementation: 10 December 2026). This Code will impose specific requirements on organizations collecting children&apos;s data online.</p>
        <p>We are currently assessing our compliance with the draft Code and will update this Privacy Policy as the Code is finalized. We are preparing to implement requirements including:</p>
        <ul>
          <li>Simplified privacy notices for children</li>
          <li>Default-to-private settings for children&apos;s data</li>
          <li>Restrictions on use of children&apos;s data for profiling and algorithmic decision-making</li>
          <li>Enhanced consent mechanisms for sensitive children&apos;s data</li>
          <li>Regular review of algorithmic recommendations</li>
          <li>Transparency about data sharing with third parties</li>
        </ul>
        <p>Baby Bloom will provide an update to this Privacy Policy once the Code is finalized (expected April 2027). Parents and professionals will be notified of material changes to our children&apos;s data handling practices.</p>

        <hr />

        <h2>20. Changes to This Policy</h2>
        <p>We may update this Privacy Policy from time to time. We will notify you of material changes by email and/or in-platform notification at least 14 days before the changes take effect.</p>
        <p>The &ldquo;Last updated&rdquo; date at the top of this policy indicates when it was most recently revised.</p>

        <hr />

        <h2>21. Privacy Officer Contact</h2>
        <p>If you have questions about this Privacy Policy, requests for access or correction, or complaints about our privacy practices, please contact:</p>
        <p><strong>Privacy Officer</strong><br />
        Baby Bloom, Sydney<br />
        ABN: 17 463 812 867<br />
        Address: 19 St Neot Avenue, Sydney NSW 2011</p>
        <p><strong>Contact Channels:</strong></p>
        <ul>
          <li><strong>General Privacy Inquiries:</strong> <a href="mailto:contact@babybloomsydney.com.au">contact@babybloomsydney.com.au</a></li>
          <li><strong>Data Access/Correction Requests:</strong> <a href="mailto:compliance@babybloomsydney.com.au">compliance@babybloomsydney.com.au</a></li>
          <li><strong>Privacy Complaints:</strong> <a href="mailto:compliance@babybloomsydney.com.au">compliance@babybloomsydney.com.au</a></li>
          <li>Website: <Link href="/legal">https://babybloomsydney.com.au/legal</Link></li>
        </ul>
        <p>We are committed to protecting your privacy and will respond to all inquiries within 10 business days.</p>

        <hr />

        <p><em>This document should be reviewed by a qualified legal professional before publication.</em></p>
      </div>
    </article>
  );
}
